### ISSUE TITLE
Hire someone for make this library works to my altcoin

### ISSUE THREAD

**Issue by coingeek** [Bit-Wasp/bitcoin-lib-php#83] opened 2015-04-06 07:04 UTC
Dear All,
Anyone can do this job, I can hire him.

I need  this library working to my Altcoin, 
I can give you my source code,

I am willing to pay 1 BTC, when that works,

Regards,

**Comment by rubensayshi** [comment] 2015-04-07 15:31
Hey @coingeek I noticed you made the same ticket on bitcoinjs-lib: https://github.com/bitcoinjs/bitcoinjs-lib/issues/391

We'd love to help but considering you have the exact same problem with bitcoinjs-lib as with bitcoin-lib-php I'm pretty sure you're doing something wrong and that it's not a bug with the libraries.

If you want someone to take a look at it, share the code for the altcoin, because that's the stuff that is important to figure this out ...

also, I don't like meddling with someones business, but I personally am a strong believer that unless you're an amazing C++ developer who's making an altcoin with some super cool new features that you're better off just using bitcoin for transfering value.  
If you think you need an altcoin for doing something with tokens, crowdfunding or w/e, take a look at coloredcoins or counterparty ;-)

**Comment by coingeek** [comment] 2015-04-07 18:35
Yes, that right.
I tested both library, when execute the rawtransaction from both library, i got the same error, signatverify failed.

i do not know why,
i can share source code of the coin.

regards,

**Comment by coingeek** [comment] 2015-04-07 18:51
I can share the source code as private, if anyone like me to hire him,
this my email to share the source code,
coingeek@hotmail.com
I will pay in bitcoin.
Regards,

**Comment by afk11** [comment] 2015-04-13 19:03
I am closing this.

**Closed by afk11** 2015-04-13 19:03 UTC
